### PR TITLE
Support `Windows.Foundation.Collections`

### PR DESCRIPTION
**Pull request by Sunbreak**

### CODE REVIEW

**Comment by Sunbreak** [comment]
`IVectorView` doesn't inherit `IInspectable` either, similiar to https://github.com/timsneath/win32/pull/246#discussion_r649641732

Possible related: https://github.com/timsneath/winmd/issues/44

**Comment by Sunbreak** [comment]
Rebased onto main but found `generate_winrt_apis.dart` disabled at https://github.com/timsneath/win32/commit/6d89d00e64ab08d065b6ef82d25ecdaeee965649

```bat
echo Generating Windows Runtime classes from Windows metadata [DISABLED]
rem call dart %~dp0metadata\generate_winrt_apis.dart %~dp0..\lib\src\com
echo.
```

@timsneath Any plan to re-enable it?

**Comment by timsneath** [comment]
Thank you! 

Yeah, I need to get back to the WinRT side in earnest now. I've been completely retooling my code generation infra in the `namespace` branch; I temporarily disabled this part so I could get the COM infra up and running. It's time for me to pull this work together and have another crack at the more complex generic- and async-driven WinRT APIs.

**Comment by timsneath** [comment]
Closing this now that @halildurmus has manually implemented these classes and they're available in main!

**Pull request closed without merging**
