### PR TITLE
[Draft] Generate full Win32 binding from metadata

### PR DESCRIPTION
**Pull request by timsneath**
Early draft of namespace work

### CODE REVIEW

**Comment by DanTup** [comment]
> Revert "Run generate after @DanTup's fixes" 

Uh-oh, did my changes break something?

**Comment by timsneath** [comment]
No, not at all! I accidentally checked the generated code into this branch, when I intended it to be only in the `v3` branch. Hopefully I kept your code and just reverted the auto-generated code.

**Comment by DanTup** [comment]
Ah, phew!

> Hopefully I kept your code and just reverted the auto-generated code.

Yep!

**Comment by timsneath** [comment]
Abandoning this for now, having merged most of the key work from `namespace` to `main`.

**Pull request closed without merging**
