### PR TITLE
Hide Char in preparation for new package:ffi

### PR DESCRIPTION
**Pull request by Sunbreak**
Signed-off-by: Sunbreak <sunbreak.wang@gmail.com>

### CODE REVIEW

**Comment by Sunbreak** [comment]
Since https://pub.dev/packages/ffi/versions/1.2.0-dev.0 `Char` is inside `package:ffi` according to https://github.com/dart-lang/ffi/pull/128

Related issue: https://github.com/timsneath/win32/issues/349

**Comment by timsneath** [comment]
This would have been a great patch, but we actually decided to not ship `Char` in package:ffi and then move it to dart:ffi. We discovered we were causing a lot of name clashes, so we [retracted 1.2.0](https://github.com/dart-lang/ffi/issues/133) and are going to just ship the new `Char` data type in dart:ffi itself in Dart 2.17.0. 

As you note, this continues to cause a name clash for the prerelease version, but there are obviously no guarantees that prerelease code is bug-free. I may change the upper bound of win32's dependency on package:ffi to avoid version 1.2.0-dev.0, but even that doesn't solve for people who already have existing versions. 

@dcharkes should we retract 1.2.0-dev.0 as well as 1.2.0, just for completeness? I also saw [this isolated incident](https://github.com/flutter/flutter/issues/98088) in the Flutter issue database.

**Comment by dcharkes** [comment]
> @dcharkes should we retract 1.2.0-dev.0 as well as 1.2.0, just for completeness?

ffigen's dev release depends on it, and people are experimenting with it and finding bugs. So, I'd say no.

> I also saw [this isolated incident](https://github.com/flutter/flutter/issues/98088) in the Flutter issue database.

Pub should never select pre-releases by itself. So maybe the bug reported upgraded his project right in the time 1.2.0 stable was live?

**Comment by timsneath** [comment]
These types have landed in 2.17 (not yet released to stable), and they have been renamed to `UnsignedChar` and `SignedChar`, which solves the problem of name clashes altogether. See https://api.dart.dev/be/184424/dart-ffi/dart-ffi-library.html. 

As a result, I'm closing this PR -- hope that's OK?

**Pull request closed without merging**
