### PR TITLE
[Chore] Bump version to v4.0.1

### PR DESCRIPTION
**Pull request by timsneath**
@halildurmus I'm thinking that this is worthy of a major version increment, given the changes made to COM object destruction. Do you agree? 

Changes:

- Incremented version to 4.0.0
- Updated `CHANGELOG.md` with commits
- Updated struct size tests with newly added structs

### CODE REVIEW

**Comment by halildurmus** [comment]
> @halildurmus I'm thinking that this is worthy of a major version increment, given the changes made to COM object destruction. Do you agree?

I agree.

**Review by halildurmus — APPROVED** [review]

**Comment by timsneath** [comment]
I've published this but I'm getting a nasty error from the pub analyzer: https://pub.dev/packages/win32/versions/4.0.0/score. I've escalated this internally, but not sure if there's anyone around. I'll probably revert the upper version bump and republish as v4.0.1 out of this same branch, just FYI, @halildurmus.

**Comment by halildurmus** [comment]
> I've published this but I'm getting a nasty error from the pub analyzer: https://pub.dev/packages/win32/versions/4.0.0/score. I've escalated this internally, but not sure if there's anyone around. I'll probably revert the upper version bump and republish as v4.0.1 out of this same branch, just FYI, @halildurmus.

I see, thanks!

**Comment by timsneath** [comment]
Looks like https://github.com/dart-lang/pana/pull/1183 is the culprit. Fix is in, but probably not rolled out to the production site due to the holidays.

**Pull request merged**
